In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_demographics = pd.read_excel("Telco_customer_churn_demographics.xlsx")
df_location = pd.read_excel("Telco_customer_churn_location.xlsx")
df_services = pd.read_excel("Telco_customer_churn_services.xlsx")
df_status = pd.read_excel("Telco_customer_churn_status.xlsx")

In [3]:
def safe_merge(df_left, df_right):
    common_cols = set(df_left.columns) & set(df_right.columns) - {'Customer ID'}
    df_right_clean = df_right.drop(columns=common_cols)
    return df_left.merge(df_right_clean, on='Customer ID', how='outer')

df_merged = safe_merge(df_demographics, df_location)
df_merged = safe_merge(df_merged, df_services)
df_merged = safe_merge(df_merged, df_status)

In [4]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 55 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Customer ID                        7043 non-null   object 
 1   Count                              7043 non-null   int64  
 2   Gender                             7043 non-null   object 
 3   Age                                7043 non-null   int64  
 4   Under 30                           7043 non-null   object 
 5   Senior Citizen                     7043 non-null   object 
 6   Married                            7043 non-null   object 
 7   Dependents                         7043 non-null   object 
 8   Number of Dependents               7043 non-null   int64  
 9   Location ID                        7043 non-null   object 
 10  Country                            7043 non-null   object 
 11  State                              7043 non-null   objec

In [5]:
df_merged.describe(include='all')

,Customer ID,Count,Gender,Age,Under 30,Senior Citizen,Married,Dependents,Number of Dependents,Location ID,...,Total Revenue,Status ID,Satisfaction Score,Customer Status,Churn Label,Churn Value,Churn Score,CLTV,Churn Category,Churn Reason
count,7043,7043.0,7043,7043.000000,7043,7043,7043,7043,7043.000000,7043,...,7043.000000,7043,7043.000000,7043,7043,7043.000000,7043.000000,7043.000000,1869,1869
unique,7043,NaN,2,NaN,2,2,2,2,NaN,7043,...,NaN,7043,NaN,3,2,NaN,NaN,NaN,5,20
top,9995-HOTOH,NaN,Male,NaN,No,No,No,No,NaN,CRAMQJ1493,...,NaN,UKMXFW1552,NaN,Stayed,No,NaN,NaN,NaN,Competitor,Competitor had better devices
freq,1,NaN,3555,NaN,5642,5901,3641,5416,NaN,1,...,NaN,1,NaN,4720,5174,NaN,NaN,NaN,841,313
mean,NaN,1.0,NaN,46.509726,NaN,NaN,NaN,NaN,0.468692,NaN,...,3034.379056,NaN,3.244924,NaN,NaN,0.265370,58.505040,4400.295755,NaN,NaN
std,NaN,0.0,NaN,16.750352,NaN,NaN,NaN,NaN,0.962802,NaN,...,2865.204542,NaN,1.201657,NaN,NaN,0.441561,21.170031,1183.057152,NaN,NaN
min,NaN,1.0,NaN,19.000000,NaN,NaN,NaN,NaN,0.000000,NaN,...,21.360000,NaN,1.000000,NaN,NaN,0.000000,5.000000,2003.000000,NaN,NaN
25%,NaN,1.0,NaN,32.000000,NaN,NaN,NaN,NaN,0.000000,NaN,...,605.610000,NaN,3.000000,NaN,NaN,0.000000,40.000000,3469.000000,NaN,NaN
50%,NaN,1.0,NaN,46.000000,NaN,NaN,NaN,NaN,0.000000,NaN,...,2108.640000,NaN,3.000000,NaN,NaN,0.000000,61.000000,4527.000000,NaN,NaN
75%,NaN,1.0,NaN,60.000000,NaN,NaN,NaN,NaN,0.000000,NaN,...,4801.145000,NaN,4.000000,NaN,NaN,1.000000,75.500000,5380.500000,NaN,NaN


In [9]:
df_merged.isnull().sum()

Customer ID                             0
Count                                   0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Location ID                             0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Lat Long                                0
Latitude                                0
Longitude                               0
Service ID                              0
Quarter                                 0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                     

In [15]:
df_merged['Offer'].unique()

array([nan, 'Offer E', 'Offer D', 'Offer A', 'Offer B', 'Offer C'],
      dtype=object)

In [16]:
df_merged['Internet Type'].unique()

array(['Cable', 'Fiber Optic', 'DSL', nan], dtype=object)

In [17]:
df_merged['Churn Category'].unique()

array([nan, 'Competitor', 'Dissatisfaction', 'Other', 'Price', 'Attitude'],
      dtype=object)

In [18]:
df_merged['Churn Reason'].unique()

array([nan, 'Competitor had better devices', 'Product dissatisfaction',
       'Network reliability', 'Limited range of services',
       'Competitor made better offer', "Don't know",
       'Long distance charges', 'Attitude of service provider',
       'Attitude of support person',
       'Competitor offered higher download speeds',
       'Competitor offered more data',
       'Lack of affordable download/upload speed', 'Deceased', 'Moved',
       'Service dissatisfaction', 'Price too high',
       'Lack of self-service on Website',
       'Poor expertise of online support', 'Extra data charges',
       'Poor expertise of phone support'], dtype=object)

In [10]:
df_merged.duplicated().sum()

np.int64(0)